### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by jpeter42** [spin-scenario/spin-scenario#2]
Following the instruction to build spin-scenario from source (under ArchLinux) - https://spin-scenario.readthedocs.io/en/latest/development.html - 

mkdir build
cd build
cmake ..
make

the last line (make) fails with:
`
In file included from ~/spin-scenario/spin-scenario/src/kernel/seq/trapezoid_gradient.h:15,
                 from ~/spin-scenario/spin-scenario/src/kernel/seq/trapezoid_gradient.cpp:13:
~/spin-scenario/spin-scenario/src/kernel/seq/interval_tree.h: In function ‘std::string& ssl::seq::operator<<(std::string&, ssl::seq::Interval<T, K>&)’:
~/spin-scenario/spin-scenario/src/kernel/seq/interval_tree.h:45:7: error: no match for ‘operator<<’ (operand types are ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} and ‘const char [10]’)
   45 |   out << "interval(" << i.start << ", " << i.stop << "): " << i.value;
      |   ~~~ ^~ ~~~~~~~~~~~
      |   |      |
      |   |      const char [10]
      |   std::string {aka std::__cxx11::basic_string<char>}
~/spin-scenario/spin-scenario/src/kernel/seq/interval_tree.h:44:14: note: candidate: ‘template<class T, class K> std::string& ssl::seq::operator<<(std::string&, ssl::seq::Interval<T, K>&)’
   44 | std::string &operator<<(std::string &out, Interval<T, K> &i) {
      |              ^~~~~~~~
~/spin-scenario/spin-scenario/src/kernel/seq/interval_tree.h:44:14: note:   template argument deduction/substitution failed:
~/spin-scenario/spin-scenario/src/kernel/seq/interval_tree.h:45:10: note:   mismatched types ‘ssl::seq::Interval<T, K>’ and ‘const char [10]’
   45 |   out << "interval(" << i.start << ", " << i.stop << "): " << i.value;
      |          ^~~~~~~~~~~
`
I compiled a year or so ago and there was no error. -

**Comment by spin-scenario** [comment]
Can you share me which version of spin-scenario you compiled? The latest source code from the master?

**Comment by ghost** [comment]
Dear Yan Chan,

Yes, I run on yesterday's code (but I tested some weeks ago with the same error). 

something with this template in interval_tree.h might be wrong (sadly, I am not a C++ programmer and I don't even understand the code):

template<class T, typename K>
std::string &operator<<(std::string &out, Interval<T, K> &i) {
   out << "interval(" << i.start << ", " << i.stop << "): " << i.value;
   return out;
} 

/home/jpeter/opt/spin-scenario/spin-scenario/src/kernel/seq/interval_tree.h:45:7: error: no match for ‘operator<<’ (operand types are ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} and ‘const char [10]’)
    45 |   out << "interval(" << i.start << ", " << i.stop << "): " << i.value;
       |   ~~~ ^~ ~~~~~~~~~~~
       |   |      |
       |   |      const char [10]
       |   std::string {aka std::__cxx11::basic_string<char>}

There are 'sol' related follow up errors (probably) due to this.


I was able to compile the code about a year ago. However it stopped working after updating the Linux system.

Thank you very much!!

Best regards from Heidelberg

Joerg



On 20-11-04 21:25, Yan Chang wrote:
>Can you share me which version of spin-scenario you compiled? The latest source code from the master?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/spin-scenario/spin-scenario/issues/2#issuecomment-722149981

--
Dr. Jörg Peter
Div. Medical Physics in Radiology
Functional and Molecular Emission Computed Tomography

German Cancer Research Center (DKFZ)
Foundation under Public Law
Im Neuenheimer Feld 280
69120 Heidelberg
Germany
phone: +49 6221 42-2607 (office), 42-4774 (laboratory) 

j.peter@dkfz.de
http://www.dkfz.de/en/medphysrad/index.php

Management Board: Prof. Dr. Michael Baumann, Ursula Weyrich
VAT-ID No.: DE143293537

**Comment by spin-scenario** [comment]
Dear Joerg,

I suppose we have to modify the CMakeLists.txt and other to fix it, because the 3rd-party library [Sol ](https://github.com/ThePhD/sol2)(used for easy scripting) has been updated, it uses higher C++ standard. 

Also, for the latest unstable version I only tested it on Windows (Visual Studio), I will complie it tonight on Linux (Ubuntu) , try to fix the bug and update the source. Thanks for your interest in spin-scenario.

Regards,

Yan

**Comment by ghost** [comment]
Excellent Yan - and thank you very much!!

Joerg

On 20-11-04 22:03, Yan Chang wrote:
>Dear Joerg,
>
>I suppose we have to modify the CMakeLists.txt and other to fix it, because the 3rd-party library [Sol ](https://github.com/ThePhD/sol2)(used for easy scripting) has been updated, it uses higher C++ standard.
>
>Also, for the latest unstable version I only tested it on Windows (Visual Studio), I will complie it tonight on Linux (Ubuntu) , try to fix the bug and update the source. Thanks for your interest in spin-scenario.
>
>Regards,
>
>Yan
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/spin-scenario/spin-scenario/issues/2#issuecomment-722162203

--
Dr. Jörg Peter
Div. Medical Physics in Radiology
Functional and Molecular Emission Computed Tomography

German Cancer Research Center (DKFZ)
Foundation under Public Law
Im Neuenheimer Feld 280
69120 Heidelberg
Germany
phone: +49 6221 42-2607 (office), 42-4774 (laboratory) 

j.peter@dkfz.de
http://www.dkfz.de/en/medphysrad/index.php

Management Board: Prof. Dr. Michael Baumann, Ursula Weyrich
VAT-ID No.: DE143293537

**Comment by spin-scenario** [comment]
Dear Joerg,
I have encountered the same problem when I switch to Ubuntu. The bug can be simply fixed by comment the [discarded function](https://github.com/spin-scenario/spin-scenario/commit/76e1dd79683d230110f137c3037390bd88291a50) in `interval_tree.h`. Please update the code and try it again. It works for me on Ubuntu 20.04 LTS (Linux version 5.4.0-42-generic gcc version 9.3.0).

**Comment by ghost** [comment]
Dear Yan,

Thank you very very much!! 

Now, it compiles successfully :-) 

However, when executing it troughs the following error:

spin-scenario: symbol lookup error: spin-scenario: undefined symbol: _ZN3ssl7utility13win_shape_mapB5cxx11Ev

What could that be?

Thank you again for looking into it and have a nice day

Joerg


On 20-11-05 06:18, Yan Chang wrote:
>Dear Joerg,
>I have encountered the same problem when I switch to Ubuntu. The bug can be simply fixed by comment the [discarded function](https://github.com/spin-scenario/spin-scenario/commit/76e1dd79683d230110f137c3037390bd88291a50) in `interval_tree.h`. Please update the code and try it again. It works for me on Ubuntu 20.04 LTS (Linux version 5.4.0-42-generic gcc version 9.3.0).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/spin-scenario/spin-scenario/issues/2#issuecomment-722406836

--
Dr. Jörg Peter
Div. Medical Physics in Radiology
Functional and Molecular Emission Computed Tomography

German Cancer Research Center (DKFZ)
Foundation under Public Law
Im Neuenheimer Feld 280
69120 Heidelberg
Germany
phone: +49 6221 42-2607 (office), 42-4774 (laboratory) 

j.peter@dkfz.de
http://www.dkfz.de/en/medphysrad/index.php

Management Board: Prof. Dr. Michael Baumann, Ursula Weyrich
VAT-ID No.: DE143293537

**Comment by spin-scenario** [comment]
It indicates that spin-scenario linked to a different dynamic lib (.so). Could you delete the old build folder, create a new one and complie it again, then run spin-scenario directly from the build folder, e.g. open terminal, and type: `./spin-scenario` to see if it works. 

You may also use `ldd spin-scenario` to locate and share me the .so path. Thank you.

**Comment by ghost** [comment]
Thank you, Yan, a lot! 

I can run spin-scenario with

$ LD_LIBRARY_PATH=~/opt/spin-scenario/build/ ~/opt/spin-scenario/build/spin-scenario

(and linking the hard-coded config file for now).

At this point, you solved the problem quite well!!

Thank you much!

Joerg

On 20-11-05 19:32, Yan Chang wrote:
>It indicates that spin-scenario linked to a different dynamic lib (.so). Could you delete the old build folder, create a new one and complie it again, then run spin-scenario directly from the build folder, e.g. open terminal, and type: `./spin-scenario` to see if it works.
>
>You may also use `ldd spin-scenario` to locate and share me the .so path. Thank you.
>
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/spin-scenario/spin-scenario/issues/2#issuecomment-722789737

--
Dr. Jörg Peter
Div. Medical Physics in Radiology
Functional and Molecular Emission Computed Tomography

German Cancer Research Center (DKFZ)
Foundation under Public Law
Im Neuenheimer Feld 280
69120 Heidelberg
Germany
phone: +49 6221 42-2607 (office), 42-4774 (laboratory) 

j.peter@dkfz.de
http://www.dkfz.de/en/medphysrad/index.php

Management Board: Prof. Dr. Michael Baumann, Ursula Weyrich
VAT-ID No.: DE143293537
